---
sidebar: sidebar 
permalink: solutions/anf-oracle.html 
keywords: bluexp automation catalog, netapp automation solutions, azure, azure netapp files, oracle 
summary: 您可以使用此自动化解决方案配置Azure NetApp Files卷并在可用虚拟机上安装Oracle。然后、Oracle会使用这些卷进行数据存储。 
---
= 使用Azure NetApp Files安装Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用此自动化解决方案配置Azure NetApp Files卷并在可用虚拟机上安装Oracle。然后、Oracle会使用这些卷进行数据存储。

.关于该解决方案
概括地说、此解决方案提供的自动化代码将执行以下操作：

* 在Azure上设置NetApp帐户
* 在Azure上设置存储容量池
* 根据定义配置Azure NetApp Files卷
* 创建挂载点
* 将Azure NetApp Files卷挂载到挂载点
* 在Linux服务器上安装Oracle
* 创建侦听器和数据库
* 创建可插拔数据库(PDB)
* 启动侦听器和Oracle实例
* 安装并配置 `azacsnap`实用程序以创建快照


.开始之前
要完成安装、您必须满足以下条件：

* 您需要通过BlueXP  Web UI下载 https://console.bluexp.netapp.com/automationCatalog["使用Azure NetApp Files的Oracle"^]自动化解决方案。该解决方案打包为file `na_oracle19c_deploy-master.zip`。
* 具有以下特征的Linux VM：
+
** RHEL 8 (Standard"(标准) D8s_v3-rRHEL 8)
** 部署在用于Azure NetApp Files配置的同一个Azure虚拟网络上


* Azure帐户


该自动化解决方案以映像形式提供、并使用Docker和Docker构成运行。您需要按照如下所述在Linux虚拟机上安装这两个组件。

您还应使用命令向RedHat注册此虚拟机 `sudo subscription-manager register`。命令将提示您输入帐户凭据。如果需要、您可以在\https://developers.redhat.com/.上创建帐户



== 第1步：安装和配置Docker

在RHEL 8 Linux虚拟机中安装和配置Docker。

.步骤
. 使用以下命令安装Docker软件。
+
[source, cli]
----
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install docker-ce --nobest -y
----
. 启动Docker并显示版本以确认安装成功。
+
[source, cli]
----
systemctl start docker
systemctl enable docker
docker --version
----
. 添加具有关联用户的所需Linux组。
+
首先检查Linux系统中是否存在组*Docker *。如果没有、请创建组并添加用户。默认情况下、当前shell用户将添加到组中。

+
[source, cli]
----
sudo groupadd docker
sudo usermod -aG docker $USER
----
. 激活新的组和用户定义
+
如果您使用用户创建了新组、则需要激活这些定义。要执行此操作、您可以注销Linux、然后重新进入。或者、您可以运行以下命令。

+
[source, cli]
----
newgrp docker
----




== 第2步：安装Docker配置和NFS实用程序

安装和配置Docker配置以及NFS实用程序软件包。

.步骤
. 安装Docker配置并显示版本以确认安装成功。
+
[source, cli]
----
dnf install curl -y
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
----
. 安装NFS实用程序软件包。
+
[source, cli]
----
sudo yum install nfs-utils
----




== 第3步：下载Oracle安装文件

下载所需的Oracle安装和修补程序文件以及 `azacsnap`实用程序。

.步骤
. 根据需要登录到Oracle帐户。
. 下载以下文件。
+
[cols="65,35"]
|===
| 文件 | 说明 


| LINUX.X64_193000_db_home.zip | 基础安装程序 


| p31281355_190000_Linux-x86-64.zip | 安装了一个插片 


| p6880880_190000_Linux-x86-64.zip | 请选择12.2.0.1.23版 


| azacsnap_installer_v5.0.run | azacsnap"安装程序 
|===
. 将所有安装文件放在文件夹中 `/tmp/archive`。
. 确保数据库服务器上的所有用户都对文件夹具有完全访问权限(读取、写入、执行) `/tmp/archive`。




== 第4步：准备Docker映像

您需要提取并加载随自动化解决方案提供的Docker映像。

.步骤
. 将解决方案文件复制 `na_oracle19c_deploy-master.zip`到要运行自动化代码的虚拟机。
+
[source, cli]
----
scp -i ~/<private-key.pem> -r na_oracle19c_deploy-master.zip user@<IP_ADDRESS_OF_VM>
----
+
输入参数 `private-key.pem`是用于Azure虚拟机身份验证的私钥文件。

. 导航到包含解决方案文件的正确文件夹、然后解压缩该文件。
+
[source, cli]
----
unzip na_oracle19c_deploy-master.zip
----
. 导航到通过解压缩操作创建的新文件夹 `na_oracle19c_deploy-master`、并列出文件。您应看到文件 `ora_anf_bck_image.tar`。
+
[source, cli]
----
ls -lt
----
. 加载Docker映像文件。加载操作通常应在几秒钟内完成。
+
[source, cli]
----
docker load -i ora_anf_bck_image.tar
----
. 确认Docker映像已加载。
+
[source, cli]
----
docker images
----
+
您应看到标记为的 `latest`Docker映像 `ora_anf_bck_image`。

+
[listing]
----
   REPOSITORY          TAG       IMAGE ID      CREATED      SIZE
ora_anf_bck_image    latest   ay98y7853769   1 week ago   2.58GB
----




== 第5步：创建外部卷

您需要一个外部卷来确保Terraform状态文件和其他重要文件是永久性的。必须为Terraform提供这些文件、才能运行工作流和部署。

.步骤
. 在Docker撰写之外创建外部卷。
+
请确保先更新卷名称、然后再运行命令。

+
[source, cli]
----
docker volume create <VOLUME_NAME>
----
. 使用命令将外部卷的路径添加到环境文件中 `.env`：
+
`PERSISTENT_VOL=path/to/external/volume:/ora_anf_prov`(英文)

+
请务必保留现有文件内容和冒号格式。例如：

+
[source, cli]
----
PERSISTENT_VOL= ora_anf _volume:/ora_anf_prov
----
. 更新Terraform变量。
+
.. 导航到文件夹 `ora_anf_variables`。
.. 确认存在以下两个文件： `terraform.tfvars`和 `variables.tf`。
.. 根据环境需要更新中的值 `terraform.tfvars`。






== 第6步：安装Oracle

现在、您可以配置和安装Oracle。

.步骤
. 使用以下命令序列安装Oracle。
+
[source, cli]
----
docker-compose up terraform_ora_anf
bash /ora_anf_variables/setup.sh
docker-compose up linux_config
bash /ora_anf_variables/permissions.sh
docker-compose up oracle_install
----
. 重新加载您的Bash变量，并通过显示的值进行确认 `ORACLE_HOME`。
+
.. `cd /home/oracle`
.. `source .bash_profile`
.. `echo $ORACLE_HOME`


. 您应该能够登录到Oracle。
+
[source, cli]
----
sudo su oracle
----




== 第7步：验证Oracle安装

您应确认Oracle安装成功。

.步骤
. 登录到Linux Oracle服务器并显示Oracle进程列表。这将确认安装按预期完成、并且Oracle数据库正在运行。
+
[source, cli]
----
ps -ef | grep ora
----
. 登录到数据库以检查数据库配置并确认正确创建了PDB。
+
[source, cli]
----
sqlplus / as sysdba
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0
----
. 执行几个简单的SQL命令以确认数据库可用。
+
[source, sql]
----
select name, log_mode from v$database;
show pdbs.
----




== 第8步：安装azacsnap"实用程序并执行快照备份

要执行快照备份、您需要安装并运行此 `azacsnap`实用程序。

.步骤
. 安装容器。
+
[source, sql]
----
docker-compose up azacsnap_install
----
. 切换到Snapshot用户帐户。
+
[source, sql]
----
su - azacsnap
execute /tmp/archive/ora_wallet.sh
----
. 配置存储备份详细信息文件。这将创建 `azacsnap.json`配置文件。
+
[source, sql]
----
cd /home/azacsnap/bin/
azacsnap -c configure –-configuration new
----
. 执行快照备份。
+
[source, sql]
----
azacsnap -c backup –-other data --prefix ora_test --retention=1
----




== 第9步：(可选)将内部PDB迁移到云

您可以选择将内部PDB迁移到云。

.步骤
. 根据环境需要在文件中设置变量 `tfvars`。
. 迁移PDB。
+
[source, cli]
----
docker-compose -f docker-compose-relocate.yml up
----

