---
sidebar: sidebar 
permalink: solutions/cvo-aws-burst-to-cloud.html 
keywords: bluexp automation catalog, netapp automation solutions, aws, cloud volumes ontap, burst to cloud 
summary: 本文支持NetApp Cloud Volumes ONTAP for AWS 自动化解决方案， NetApp客户可从NetApp控制台自动化目录中获取该解决方案。 
---
= 适用于AWS的Cloud Volumes ONTAP—突发到云
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本文支持NetApp Cloud Volumes ONTAP for AWS 自动化解决方案， NetApp客户可从NetApp控制台自动化目录中获取该解决方案。

适用于AWS的Cloud Volumes ONTAP自动化解决方案可使用Terraform自动执行适用于AWS的Cloud Volumes ONTAP容器化部署、让您无需任何手动干预即可快速部署适用于AWS的Cloud Volumes ONTAP。

.开始之前
* 您必须下载link:https://console.netapp.com/automationCatalog["Cloud Volumes ONTAP AWS—突发到云"^]通过控制台 Web UI 实现自动化解决方案。该解决方案打包为 `cvo_aws_flexcache.zip`。
* 您必须在与Cloud Volumes ONTAP相同的网络上安装Linux VM。
* 安装Linux VM后、必须按照本解决方案中的步骤安装所需的依赖项。




== 第1步：安装Docker和Docker构建



=== 安装 Docker

以下步骤以Ubuntu 20.04 Debian Linux分发软件为例。您运行的命令取决于您使用的Linux分发软件。请参阅适用于您的配置的特定Linux分发软件文档。

.步骤
. 运行以下命令以安装Docker `sudo`：
+
[source, cli]
----
sudo apt-get update
sudo apt-get install apt-transport-https cacertificates curl gnupg-agent software-properties-common curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
sudo apt-key add -
sudo add-apt-repository “deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable”
sudo apt-get update
sudo apt-get install dockerce docker-ce-cli containerd.io
----
. 验证安装。
+
[source, cli]
----
docker –version
----
. 验证是否已在Linux系统上创建名为"Docker "的组。如有必要、请创建组：
+
[source, cli]
----
sudo groupadd docker
----
. 将需要访问Docker的用户添加到组：
+
[source, cli]
----
sudo usermod -aG docker $(whoami)
----
. 您的更改将在注销并重新登录到终端后应用。或者、您也可以立即应用更改：
+
[source, cli]
----
newgrp docker
----




=== 安装Docker配置

.步骤
. 运行以下命令以安装Docker配置 `sudo`：
+
[source, cli]
----
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
----
. 验证安装。
+
[source, cli]
----
docker-compose –version
----




== 第2步：准备Docker映像

.步骤
. 将此文件夹复制 `cvo_aws_flexcache.zip`到要用于部署Cloud Volumes ONTAP的Linux VM：
+
[source, cli]
----
scp -i ~/<private-key>.pem -r cvo_aws_flexcache.zip <awsuser>@<IP_ADDRESS_OF_VM>:<LOCATION_TO_BE_COPIED>
----
+
** `private-key.pem`是用于无密码登录的私钥文件。
** `awsuser`是虚拟机用户名。
** `IP_ADDRESS_OF_VM`是VM IP地址。
** `LOCATION_TO_BE_COPIED`是复制文件夹的位置。


. 提取 `cvo_aws_flexcache.zip`文件夹。您可以提取当前目录或自定义位置中的文件夹。
+
要解压缩当前目录中的文件夹、请运行：

+
[source, cli]
----
unzip cvo_aws_flexcache.zip
----
+
要在自定义位置提取文件夹、请运行：

+
[source, cli]
----
unzip cvo_aws_flexcache.zip -d ~/<your_folder_name>
----
. 解压缩内容后、导航到 `CVO_Aws_Deployment`文件夹并运行以下命令以查看文件：
+
[source, cli]
----
 ls -la
----
+
您应看到一个文件列表、类似于以下示例：

+
[listing]
----
total 32
    drwxr-xr-x   8 user1  staff   256 Mar 23 12:26 .
    drwxr-xr-x   6 user1  staff   192 Mar 22 08:04 ..
    -rw-r--r--   1 user1  staff   324 Apr 12 21:37 .env
    -rw-r--r--   1 user1  staff  1449 Mar 23 13:19 Dockerfile
    drwxr-xr-x  15 user1  staff   480 Mar 23 13:19 cvo_Aws_source_code
    drwxr-xr-x   4 user1  staff   128 Apr 27 13:43 cvo_Aws_variables
    -rw-r--r--   1 user1  staff   996 Mar 24 04:06 docker-compose-deploy.yml
    -rw-r--r--   1 user1  staff  1041 Mar 24 04:06 docker-compose-destroy.yml
----
. 找到 `cvo_aws_flexcache_ubuntu_image.tar`文件。其中包含部署Cloud Volumes ONTAP for AWS所需的Docker映像。
. 解压缩文件：
+
[source, cli]
----
docker load -i cvo_aws_flexcache_ubuntu_image.tar
----
. 等待几分钟、等待Docker映像加载完毕、然后验证是否已成功加载Docker映像：
+
[source, cli]
----
docker images
----
+
您应看到一个名为且带有 `latest`标记的Docker映像 `cvo_aws_flexcache_ubuntu_image`、如以下示例所示：

+
[listing]
----
REPOSITORY                            TAG        IMAGE ID       CREATED      SIZE
 cvo_aws_flexcache_ubuntu_image     latest    18db15a4d59c   2 weeks ago   1.14GB
----
+

NOTE: 您可以根据需要更改Docker映像名称。如果更改Docker映像名称、请确保在和 `docker-compose-destroy`文件中更新Docker映像名称 `docker-compose-deploy`。





== 第3步：创建环境变量文件

在此阶段，您必须创建两个环境变量文件。一个文件用于使用 AWS 访问密钥和密钥对 AWS Resource Manager API 进行身份验证。第二个文件用于设置环境变量，以使控制台 Terraform 模块能够定位和验证 AWS API。

.步骤
. 在以下位置创建 `awsauth.env`文件：
+
`path/to/env-file/awsauth.env`

+
.. 将以下内容添加到文件中 `awsauth.env`：
+
access_key=<> key_key=<>

+
格式*必须*与上面显示的格式完全相同。



. 将绝对文件路径添加到 `.env`文件中。
+
输入与环境变量对应的环境文件的 `AWS_CREDS`绝对路径 `awsauth.env`。

+
`AWS_CREDS=path/to/env-file/awsauth.env`

. 导航到该 `cvo_aws_variable`文件夹并更新凭据文件中的访问权限和机密密钥。
+
将以下内容添加到文件中：

+
aws_access_key_id <>aws_key_access_key=<>

+
格式*必须*与上面显示的格式完全相同。





== 步骤 4：注册NetApp智能服务

通过您的云提供商注册NetApp智能服务，按小时付费（PAYGO）或通过年度合同付费。NetApp智能服务包括NetApp备份和恢复、 Cloud Volumes ONTAP、 NetApp云分层、 NetApp勒索软件恢复和NetApp灾难恢复。NetApp数据分类包含在您的订阅中，无需额外付费。

.步骤
. 从 Amazon Web Services (AWS) 门户导航到 *SaaS* 并选择 *订阅NetApp智能服务*。
+
您可以使用与Cloud Volumes ONTAP相同的资源组，也可以使用不同的资源组。

. 配置NetApp控制台门户以将 SaaS 订阅导入控制台。
+
您可以直接从AWS门户配置此配置。

+
您将被重定向到控制台门户以确认配置。

. 通过选择“*保存*”确认控制台门户中的配置。




== 第5步：创建外部卷

您应创建一个外部卷、以保留Terraform状态文件和其他重要文件。您必须确保文件可供Terraform运行工作流和部署。

.步骤
. 在Docker撰写之外创建外部卷：
+
[source, cli]
----
docker volume create <volume_name>
----
+
示例：

+
[listing]
----
docker volume create cvo_aws_volume_dst
----
. 使用以下选项之一：
+
.. 向环境文件添加外部卷路径 `.env`。
+
您必须遵循以下所示的确切格式。

+
格式。

+
`PERSISTENT_VOL=path/to/external/volume:/cvo_aws`

+
示例：
`PERSISTENT_VOL=cvo_aws_volume_dst:/cvo_aws`

.. 将NFS共享添加为外部卷。
+
请确保Docker容器可以与NFS共享进行通信、并且已配置正确的权限(例如读/写权限)。

+
... 在Docker编制文件中添加NFS共享路径作为外部卷的路径、如下所示：格式：
+
`PERSISTENT_VOL=path/to/nfs/volume:/cvo_aws`

+
示例：
`PERSISTENT_VOL=nfs/mnt/document:/cvo_aws`





. 导航到 `cvo_aws_variables`文件夹。
+
您应在文件夹中看到以下变量文件：

+
** `terraform.tfvars`
** `variables.tf`


. 根据需要更改文件中的值 `terraform.tfvars`。
+
修改文件中的任何变量值时、您必须阅读特定的支持文档 `terraform.tfvars`。根据地区、可用性区域以及Cloud Volumes ONTAP for AWS支持的其他因素、这些值可能会有所不同。其中包括单个节点和高可用性(HA)对的许可证、磁盘大小和VM大小。

+
控制台代理和Cloud Volumes ONTAP Terraform 模块的所有支持变量均已在 `variables.tf`文件。您必须引用 `variables.tf`在添加到文件之前 `terraform.tfvars`文件。

. 根据您的要求，您可以通过将以下选项设置为或来启用或 `false`禁用FlexCache和FlexClone `true`。
+
以下示例将启用FlexCache和FlexClone：

+
** `is_flexcache_required = true`
** `is_flexclone_required = true`






== 第6步：部署Cloud Volumes ONTAP for AWS

按照以下步骤部署Cloud Volumes ONTAP for AWS。

.步骤
. 从根文件夹中、运行以下命令以触发部署：
+
[source, cli]
----
docker-compose -f docker-compose-deploy.yml up -d
----
+
此时将触发两个容器、第一个容器部署Cloud Volumes ONTAP、第二个容器将遥测数据发送到AutoSupport。

+
第二个容器将等待、直到第一个容器成功完成所有步骤。

. 使用日志文件监控部署过程的进度：
+
[source, cli]
----
docker-compose -f docker-compose-deploy.yml logs -f
----
+
此命令可实时提供输出并捕获以下日志文件中的数据：
`deployment.log`

+
`telemetry_asup.log`

+
您可以通过使用以下环境变量编辑这些日志文件来更改其名称 `.env`：

+
`DEPLOYMENT_LOGS`

+
`TELEMETRY_ASUP_LOGS`

+
以下示例显示了如何更改日志文件名：

+
`DEPLOYMENT_LOGS=<your_deployment_log_filename>.log`

+
`TELEMETRY_ASUP_LOGS=<your_telemetry_asup_log_filename>.log`



.完成后
您可以使用以下步骤删除临时环境并清理在部署过程中创建的项目。

.步骤
. 如果您已部署FlexCache、请在变量文件中设置以下选项 `terraform.tfvars`、这样将清理FlexCache卷并删除先前创建的临时环境。
+
`flexcache_operation = "destroy"`

+

NOTE: 可能的选项包括 `deploy`和 `destroy`。

. 如果您已部署FlexClone、请在变量文件中设置以下选项 `terraform.tfvars`、这样将清理FlexClone卷并删除先前创建的临时环境。
+
`flexclone_operation = "destroy"`

+

NOTE: 可能的选项包括 `deploy`和 `destroy`。


