---
sidebar: sidebar 
permalink: solutions/fsxn-disaster-recovery.html 
keywords: bluexp automation catalog, netapp automation solutions, fsx for ontap, disaster recovery, backup 
summary: 您可以使用此自动化解决方案通过Amazon FSx for NetApp ONTAP为源系统创建灾难恢复备份。 
---
= Amazon FSx for NetApp ONTAP—灾难恢复
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用此自动化解决方案通过Amazon FSx for NetApp ONTAP为源系统创建灾难恢复备份。


NOTE: Amazon FSx for NetApp ONTAP也称为*FSx for ONTAP。

.关于该解决方案
概括地说、此解决方案提供的自动化代码将执行以下操作：

* 为ONTAP文件系统配置目标FSx
* 为文件系统配置Storage Virtual Machine (SVM)
* 在源系统和目标系统之间创建集群对等关系
* 在SnapMirror的源系统和目标系统之间创建SVM对等关系
* 创建目标卷
* 在源卷和目标卷之间创建SnapMirror关系
* 在源卷和目标卷之间启动SnapMirror传输


此自动化操作基于Docker和Docker编制、必须按如下所述将其安装在Linux虚拟机上。

.开始之前
要完成配置和配置、您必须满足以下条件：

* 您需要通过BlueXP  Web UI下载 https://console.bluexp.netapp.com/automationCatalog["Amazon FSx for NetApp ONTAP—灾难恢复"^]自动化解决方案。该解决方案打包为 `FSxN_DR.zip`。此压缩文件包含 `AWS_FSxN_Bck_Prov.zip`用于部署本文档所述解决方案的文件。
* 源系统和目标系统之间的网络连接。
* 具有以下特征的Linux VM：
+
** 基于Debian的Linux分发版
** 部署在用于FSx for ONTAP配置的同一VPC子集上


* AWS帐户。




== 第1步：安装和配置Docker

在基于Debian的Linux虚拟机中安装和配置Docker。

.步骤
. 准备环境。
+
[source, cli]
----
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent softwareproperties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
----
. 安装Docker并验证安装。
+
[source, cli]
----
sudo apt-get install docker-ce docker-ce-cli containerd.io
docker --version
----
. 添加具有关联用户的所需Linux组。
+
首先检查Linux系统中是否存在组*Docker *。如果不存在、请创建组并添加用户。默认情况下、当前shell用户将添加到组中。

+
[source, cli]
----
sudo groupadd docker
sudo usermod -aG docker $(whoami)
----
. 激活新的组和用户定义
+
如果您使用用户创建了新组、则需要激活这些定义。要执行此操作、您可以注销Linux、然后重新进入。或者、您可以运行以下命令。

+
[source, cli]
----
newgrp docker
----




== 第2步：安装Docker配置

在基于Debian的Linux虚拟机中安装Docker编制。

.步骤
. 安装Docker配置。
+
[source, cli]
----
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
----
. 验证安装是否成功。
+
[source, cli]
----
docker-compose --version
----




== 第3步：准备Docker映像

您需要提取并加载随自动化解决方案提供的Docker映像。

.步骤
. 将解决方案文件复制 `AWS_FSxN_Bck_Prov.zip`到要运行自动化代码的虚拟机。
+
[source, cli]
----
scp -i ~/<private-key.pem> -r AWS_FSxN_Bck_Prov.zip user@<IP_ADDRESS_OF_VM>
----
+
输入参数 `private-key.pem`是用于AWS虚拟机身份验证(EC2实例)的专用密钥文件。

. 导航到包含解决方案文件的正确文件夹、然后解压缩该文件。
+
[source, cli]
----
unzip AWS_FSxN_Bck_Prov.zip
----
. 导航到通过解压缩操作创建的新文件夹 `AWS_FSxN_Bck_Prov`、并列出文件。您应看到文件 `aws_fsxn_bck_image_latest.tar.gz`。
+
[source, cli]
----
ls -la
----
. 加载Docker映像文件。加载操作通常应在几秒钟内完成。
+
[source, cli]
----
docker load -i aws_fsxn_bck_image_latest.tar.gz
----
. 确认Docker映像已加载。
+
[source, cli]
----
docker images
----
+
您应看到标记为的 `latest`Docker映像 `aws_fsxn_bck_image`。

+
[listing]
----
   REPOSITORY        TAG     IMAGE ID      CREATED      SIZE
aws_fsxn_bck_image  latest  da87d4974306  2 weeks ago  1.19GB
----




== 第4步：为AWS凭据创建环境文件

您必须使用访问和机密密钥创建一个用于身份验证的本地变量文件。然后将该文件添加到该文件中 `.env`。

.步骤
. 在以下位置创建 `awsauth.env`文件：
+
`path/to/env-file/awsauth.env`

. 将以下内容添加到文件中：
+
[listing]
----
access_key=<>
secret_key=<>
----
+
格式“*必须*”与上面所示完全相同，并且和 `value`之间没有任何空格 `key`。

. 使用变量将绝对文件路径添加到此文件 `AWS_CREDS`中 `.env`。例如：
+
`AWS_CREDS=path/to/env-file/awsauth.env`





== 第5步：创建外部卷

您需要一个外部卷来确保Terraform状态文件和其他重要文件是永久性的。必须为Terraform提供这些文件、才能运行工作流和部署。

.步骤
. 在Docker撰写之外创建外部卷。
+
请确保在运行命令之前将卷名称(Last参数)更新为适当的值。

+
[source, cli]
----
docker volume create aws_fsxn_volume
----
. 使用命令将外部卷的路径添加到环境文件中 `.env`：
+
`PERSISTENT_VOL=path/to/external/volume:/volume_name`

+
请务必保留现有文件内容和冒号格式。例如：

+
[source, cli]
----
PERSISTENT_VOL=aws_fsxn_volume:/aws_fsxn_bck
----
+
而是可以使用以下命令将NFS共享添加为外部卷：

+
`PERSISTENT_VOL=nfs/mnt/document:/aws_fsx_bck`

. 更新Terraform变量。
+
.. 导航到文件夹 `aws_fsxn_variables`。
.. 确认存在以下两个文件： `terraform.tfvars`和 `variables.tf`。
.. 根据环境需要更新中的值 `terraform.tfvars`。
+
有关详细信息、请参见 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system["Terraform资源：aws_FSX_raf_File_system ONTAP"^] 。







== 第6步：部署备份解决方案

您可以部署和配置灾难恢复备份解决方案。

.步骤
. 导航到文件夹根(aws_fsxN_Bck_Prov)、然后发出配置命令。
+
[source, cli]
----
docker-compose up -d
----
+
此命令可创建三个容器。第一个容器部署FSx for ONTAP。第二个容器将创建集群对等、SVM对等和目标卷。第三个容器将创建SnapMirror关系并启动SnapMirror传输。

. 监控配置过程。
+
[source, cli]
----
docker-compose logs -f
----
+
此命令可实时提供输出，但已配置为通过文件捕获日志 `deployment.log`。您可以通过编辑这些日志文件并更新变量来更改这些文件的 `DEPLOYMENT_LOGS`名称 `.env`。


